### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by j-px** [flathub/sh.fhs.KatawaShoujoReEngineered#5]
Just tried running the game with `fallback-x11` and `wayland` sockets exposed instead of `x11`, and it worked on both Wayland and X11 GNOME 45 for me. Are there any reasons to not ship that by default?

**Comment by fat0troll** [comment]
There was problems on my side with Wayland and this game, and I decided to not ship something that untested by me.

Now I can confirm too that game runs under Wayland OK.

Permissions will be fixed with next game release.
